# Generated by Django 5.2.1 on 2026-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelroute',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('forming', '报名成团中'), ('full', '已满团')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
